package com.mojang.blaze3d.shaders;

public enum UniformType {
    FLOAT, FLOAT_VEC2, FLOAT_VEC3, FLOAT_VEC4, INT, INT_VEC2, INT_VEC3, INT_VEC4,
    FLOAT_MAT2, FLOAT_MAT3, FLOAT_MAT4, SAMPLER_2D, SAMPLER_3D, SAMPLER_CUBE, UNIFORM_BUFFER, TEXEL_BUFFER;
}
